---
- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 90
- name: Create directory structure
  win_file:
    path: "{{ dest_path }}"
    state: directory
- win_copy:
    src: "{{ exe_files_path}}/{{item}}"
    dest: "{{ dest_path }}/{{item}}"
  register: output
  with_items: "{{ file_name }}"

- name: debug
  debug:
    msg: "{{output}}"
