---
- hosts: win-hosts
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Block for copying intake form
    block:
    - include_role:
        name: ../roles/copy-exe
  - name: Block for running script
    block:
    - include_role:
          name: ../roles/MF_intake_tags
