---
- hosts: win-hosts
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Block for installion in windows
    block:
    - include_role:
        name: ../roles/copy-exe
  - name: Block for installion in windows
    block:
    - include_role:
          name: ../roles/migration-factory-executor
