version: 0.2 

phases: 
  install:
    runtime-versions:  
      nodejs: 10    
    commands:  
      - aws s3 cp s3://$DEVOPS_SCRIPTS_BUCKET/$SCRIPT_S3_PATH/buildspec_install.sh . 
      - chmod +x buildspec_install.sh && ./buildspec_install.sh   
 
  build: 
    commands:  
      - aws s3 cp s3://$DEVOPS_SCRIPTS_BUCKET/$SCRIPT_S3_PATH/buildspec_build.sh .
      - chmod +x buildspec_build.sh && ./buildspec_build.sh

  post_build: 
    commands: 
      - echo Build completed on `date`
      #- echo Sync files to S3
      #- aws s3 cp $artifactname s3://$ARTIFACT_BUCKET/$ARTIFACT_S3_FOLDER/ --sse
      #- aws s3api put-object --bucket $ARTIFACT_S3_BUCKET --key $ARTIFACT_S3_FOLDER/$artifactname --body $artifactname
        
artifacts: 
  files: 
    - dist/version.html  
    - appspec.yml   
    - ansible_deploy.sh      
    - env.txt   
  discard-paths: yes



